# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liss's Blog
email: lisset.cuevasj@gmail.com 
email2: lcuevas@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
  Mexican, Engineering student, Feminist, Outreachy Intern with Mozilla ‚ù§
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lissetcuevas.github.io/blog/" # the base hostname & protocol for your site
twitter_username: lisscuevass
github_username:  lissetcuevas

# Build settings
markdown: kramdown
